name: greet-staging

on:
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3
      - name: Print dir
        run: ls
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Download Go modules
        run: |
          go mod download
          make download-libs
          make workspace=services/greet download
          sudo make install-lint
      - name: Install curl, jq, make, zip, ping, net-tools
        run:  sudo apt-get -qq -y install curl jq build-essential zip iputils-ping net-tools
      - name: Install docker-compose
        run: make install-docker-compose
      - name: Publish to azure staging
        run: |
          curl --location --request GET 'https://func-greet-stg-ea.azurewebsites.net/api/hello' \
          --header 'x-functions-key: ${{ secrets.GREET_API_KEY }}'