name: web_notify-e2e
concurrency:
  group: web_notify-tests
  cancel-in-progress: true

on:
  push:
    paths:
      - ".github/**"
      - "libs/**"
      - "!libs/**/go.sum"
      - "services/web_notify/**"
      - "!services/web_notify/go.sum"
      - "services/go.work"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3
      - name: Print dir
        run: ls
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Download Go modules
        run: |
          go mod download
          make download-libs
          make workspace=services/web_notify download
          sudo make install-lint
      - name: Run unit tests
        run: |
          make test-libs
          make workspace=services/web_notify test
      - name: Run lint
        run: |
          make lint-libs
          make workspace=services/web_notify lint

  e2e-local-sandbox:
    runs-on: ubuntu-latest
    needs: unit-test
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3
      - name: Print dir
        run: ls
      - name: Update ubuntu
        run: sudo apt-get -qq update
      - name: Install curl, jq, make, zip, ping, net-tools
        run:  sudo apt-get -qq -y install curl jq build-essential zip iputils-ping net-tools
      - name: Install docker-compose
        run: make install-docker-compose
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Download Go modules
        run: |
          go mod download
          make download-libs
          make workspace=services/web_notify download
      - name: Build main.exe
        run: make workspace=services/web_notify build
      - name: Install and start azurite
        id: azuright
        uses: potatoqualitee/azuright@v1.1
      - name: Install azure functions
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get install azure-functions-core-tools-4
      - name: Start azure func
        run: make workspace=services/web_notify func-start &
      - name: Start azure vault emulator
        run: docker run --rm -d -p 8443:8443 --name lowkey_vault nagyesta/lowkey-vault:1.8.14
      - name: Check that daemons are running
        run: |
          netstat -nat | grep '7071' | grep LISTEN
          netstat -nat | grep '8443' | grep LISTEN
          netstat -nat | grep '10000' | grep LISTEN
      - name: POST request to enqueue subscription
        run: |
          curl --location --request POST 'http://localhost:7071/api/notifications' \
          --header 'Content-Type: application/json' \
          --header 'Connection: close' \
          --data-raw '{
              "userID": "abc@m.com",
              "company": "fakepanda",
              "notification": {
                  "title": "My title",
                  "body": "My message",
                  "icon": "My icon"
              }
          }'
